### ISSUE TITLE
help: I don't know what's the reason

### ISSUE THREAD

**Issue by Chasen-Zhang** [Menci/vite-plugin-top-level-await#10]
![image](https://user-images.githubusercontent.com/15354455/194979523-4169efdd-7c83-4b99-bd35-6944bf55b455.png)

Is there a problem with that？

![image](https://user-images.githubusercontent.com/15354455/194979705-ce665c6e-cdd8-47cd-834a-5cc1593004a7.png)

**Comment by Menci** [comment]
Please upload your project for me to reproduce.

**Comment by tommasomeli** [comment]
same error

**Comment by Menci** [comment]
@tommasomeli Do you have a reproduce project?

**Comment by timsoulm** [comment]
I'm also experiencing this same issue.

```
Uncaught (in promise) TypeError: Assignment to constant variable.
    at e (index.6b5a1eac.js:619:15764)
    at j9t (index.6b5a1eac.js:619:15994)
    at U7e (index.6b5a1eac.js:619:16259)
    at G7e (index.6b5a1eac.js:619:19782)
    at Z9t (index.6b5a1eac.js:619:19827)
    at index.6b5a1eac.js:619:20091
    at index.6b5a1eac.js:619:20312
    at index.6b5a1eac.js:710:19177
```

I can't share our whole project, but can provide a more details to help reproduce.

- It repros in production mode only, not dev mode.
- I'm on the following package versions:
  - `"vite": "^3.0.7",`
  - `"vite-plugin-top-level-await": "1.2.4",`

This is essentially what our vite.config.ts file looks like:
```
import * as babel from '@babel/core';
import react from '@vitejs/plugin-react';
import { createRequire } from 'module';
import { defineConfig, loadEnv, TransformResult } from 'vite';
import { nodePolyfills } from 'vite-plugin-node-polyfills';
import topLevelAwait from 'vite-plugin-top-level-await';
import wasm from 'vite-plugin-wasm';
import tsconfigPaths from 'vite-tsconfig-paths';

import { extractRuntimeConfig } from './src/server/utils';
const require = createRequire(import.meta.url);
const sourceRegex = /\.(j|t)sx?$/;
const tsxRegex = /\.(j|t)sx$/;
function macrosPlugin() {
    return {
        name: 'babel-macros',
        enforce: 'pre',
        async transform(source: string, filename: string) {
            if (filename.includes('node_modules')) {
                return undefined;
            }

            if (!sourceRegex.test(filename)) {
                return undefined;
            }

            const result = await babel.transformAsync(source, {
                filename,
                plugins: [
                    require.resolve('@babel/plugin-syntax-jsx'),
                    [require.resolve('@babel/plugin-syntax-typescript'), { isTSX: tsxRegex.test(filename) }],
                    require.resolve('babel-plugin-macros'),
                ],
                babelrc: false,
                configFile: false,
                sourceMaps: true,
            });
            return result as TransformResult | null;
        },
    } as const;
}

export default defineConfig(({ mode }) => {
    return {
        plugins: [react(), tsconfigPaths(), topLevelAwait(), wasm(), macrosPlugin(), nodePolyfills()]
    };
});
```

tsconfig.json file looks like this:
```
{
    "compilerOptions": {
        "target": "ESNext",
        "lib": ["dom", "dom.iterable", "esnext"],
        "allowJs": false,
        "skipLibCheck": true,
        "esModuleInterop": true,
        "allowSyntheticDefaultImports": true,
        "strict": true,
        "forceConsistentCasingInFileNames": true,
        "noFallthroughCasesInSwitch": true,
        "module": "esnext",
        "moduleResolution": "node",
        "resolveJsonModule": true,
        "isolatedModules": true,
        "noEmit": true,
        "jsx": "react-jsx",
        "baseUrl": "src",
        "incremental": true,
        "types": ["cypress"]
    },
    "include": ["src/**/*", "test/**/*", "__mocks__/*", "cypress/**/*"],
    "exclude": ["src/server"]
}
```

**Comment by qsya** [comment]
same error

**Comment by Menci** [comment]
@timsoulm @qsya Does anyone here have a reproduce?

**Comment by Menci** [comment]
Closing since no response.
