### ISSUE TITLE
TypeError: topLevelAwait is not a function

### ISSUE THREAD

**Issue by xididri** [Menci/vite-plugin-top-level-await#2]
I have an error on build (using [astro](https://github.com/withastro/astro)) when using this plugin as such:

```js
import { defineConfig } from 'astro/config';

import topLevelAwait from 'vite-plugin-top-level-await';


export default defineConfig({
	vite: {
		// build: { target: 'esnext' },
		plugins: [
			topLevelAwait({
				// The export name of top-level await promise for each chunk module
				promiseExportName: '__tla',
				// The function to generate import names of top-level await promise in each chunk module
				promiseImportName: (i) => `__tla_${i}`,
			}),
		],
	},
});
```

Full error:

```
(node:3597) UnhandledPromiseRejectionWarning: TypeError: topLevelAwait is not a function
    at file:///home/dri/code/tmc-astro/astro.config.mjs:14:4
    at ModuleJob.run (internal/modules/esm/module_job.js:146:23)
    at async Loader.import (internal/modules/esm/loader.js:165:24)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3597) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:3597) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

- vite-plugin-top-level-await v0.0.4
- astro v0.26.1 (vitejs v1.8.2)
- node v14.15.0

edit: running this on ubuntu 20.04 on WSL

**Comment by Menci** [comment]
Are you using Node.js ESM?

**Comment by Menci** [comment]
Fixed in https://github.com/Menci/vite-plugin-top-level-await/commit/34e3ba7624f428c99287fb090d3064346d6a1951.
