### ISSUE TITLE
Unexpected top-level statement "ExportDefaultExpression" in Rollup's output chunk.

### ISSUE THREAD

**Issue by adimit** [Menci/vite-plugin-top-level-await#22]
Hi. When I run `yarn build` in my project, I get the following error:

```
[vite-plugin-top-level-await] Unexpected top-level statement "ExportDefaultExpression" in Rollup's output chunk. Please open an issue at https://github.com/Menci/vite-plugin-top-level-await/issues.
error during build:
Error: Unexpected top-level statement "ExportDefaultExpression" in Rollup's output chunk. Please open an issue at https://github.com/Menci/vite-plugin-top-level-await/issues.
    at raiseUnexpectedNode (/path-to-source/src/maze/web/frontend/node_modules/vite-plugin-top-level-await/dist/utils/error.js:6:11)
    at /path-to-source/src/maze/web/frontend/node_modules/vite-plugin-top-level-await/dist/transform.js:36:49
    at Array.filter (<anonymous>)
    at transformModule (/path-to-source/src/maze/web/frontend/node_modules/vite-plugin-top-level-await/dist/transform.js:28:35)
    at /path-to-source/src/maze/web/frontend/node_modules/vite-plugin-top-level-await/dist/index.js:72:64
    at Array.map (<anonymous>)
    at Object.generateBundle (/path-to-source/src/maze/web/frontend/node_modules/vite-plugin-top-level-await/dist/index.js:69:57)
    at async Bundle.generate (file:///path-to-source/src/maze/web/frontend/node_modules/rollup/dist/es/shared/rollup.js:16747:9)
    at async file:///path-to-source/src/maze/web/frontend/node_modules/rollup/dist/es/shared/rollup.js:24977:27
    at async catchUnfinishedHookActions (file:///path-to-source/src/maze/web/frontend/node_modules/rollup/dist/es/shared/rollup.js:24066:20)
    at async doBuild (file:///path-to-source/src/maze/web/frontend/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:44518:22)
    at async build (file:///path-to-source/src/maze/web/frontend/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:44347:16)
    at async CAC.<anonymous> (file:///path-to-source/src/maze/web/frontend/node_modules/vite/dist/node/cli.js:808:9)"
```

It's reproducible with [this commit](https://github.com/adimit/amazegen/tree/83cabbe244a124aab2c88515f2dfcd41905c1739) and the following command:

```
git clone https://github.com/adimit/amazegen
cd amazegen
git checkout 83cabbe244
cd web/frontend
wasm-pack build --target bundler --release && yarn && yarn build
```

The config file looks like this:

```
import { defineConfig } from "vite";
import solidPlugin from "vite-plugin-solid";
import wasm from "vite-plugin-wasm";
import topLevelAwait from "vite-plugin-top-level-await";
import { nodePolyfills } from "vite-plugin-node-polyfills";

export default defineConfig({
  plugins: [wasm(), topLevelAwait(), solidPlugin(), nodePolyfills()],
  server: {
    port: 3000,
    fs: {
      allow: [".", "../../pkg"],
    },
  },
});
```

My node version is 16.19.0

**Comment by Menci** [comment]
Thank you. I'll check it.

**Comment by Menci** [comment]
Fixed in https://github.com/Menci/vite-plugin-top-level-await/commit/ec81ad77a73e58c1b665b4a7ec77a7f8813d5227 and released in `v1.2.3`.

**Comment by adimit** [comment]
@Menci, thank you very much. That was amazingly quick. I can confirm it worked.

**Comment by NautHnil** [comment]
@Menci I got an error related to "Rollup". Please check help me.

<img width="916" alt="image" src="https://github.com/Menci/vite-plugin-top-level-await/assets/2637746/e6da251a-ab4b-4780-b6a2-06fce96be19b">
