### ISSUE TITLE
[BUG] Transform failed with 1 error: <stdin>:1:286: ERROR: The symbol "xt" has already been declared

### ISSUE THREAD

**Issue by ztjhz** [Menci/vite-plugin-top-level-await#27]
I get the following error when I run `yarn build`.

Error message:

```
➜  FreeChatGPT git:(tiktoken) yarn build
yarn run v1.22.19
$ tsc && vite build
vite v4.1.4 building for production...
✓ 1789 modules transformed.
rendering chunks (3)...[vite-plugin-top-level-await] Transform failed with 1 error:
<stdin>:1:286: ERROR: The symbol "xt" has already been declared
error during build:
Error: Transform failed with 1 error:
<stdin>:1:286: ERROR: The symbol "xt" has already been declared
    at failureErrorWithLog (/home/nixie/FreeChatGPT/node_modules/esbuild/lib/main.js:1604:15)
    at /home/nixie/FreeChatGPT/node_modules/esbuild/lib/main.js:837:29
    at responseCallbacks.<computed> (/home/nixie/FreeChatGPT/node_modules/esbuild/lib/main.js:701:9)
    at handleIncomingPacket (/home/nixie/FreeChatGPT/node_modules/esbuild/lib/main.js:756:9)
    at Socket.readFromStdout (/home/nixie/FreeChatGPT/node_modules/esbuild/lib/main.js:677:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Source code: https://github.com/ztjhz/BetterChatGPT/tree/tiktoken

I spent a long time debugging this. I discovered that the `xt` is actually a module called `Canvg`, which is an optional dependency of another module `jspdf`. When I remove the import of `jspdf` in my source code, the compilation would work.

**Comment by ztjhz** [comment]
In addition, I am using `vite-plugin-top-level-await` because tiktoken needs `vite-plugin-wasm` which needs `vite-plugin-top-level-await`

**Comment by MinatoHikari** [comment]
same problem here

**Comment by yashash-pugalia** [comment]
+1

**Comment by Menci** [comment]
Thanks all of you. I'm sorry that I'm busy recently. I'll take a look and
fix it recently when I have time.

**Comment by Menci** [comment]
Hi! After investigation I found the issue is that the file being processed exported the same name `Canvg` as both itself and default:

```
export {
  AElement,
  AnimateColorElement,
  AnimateElement,
  AnimateTransformElement,
  BoundingBox,
  CB1,
  CB2,
  CB3,
  CB4,
  Canvg, # here
  CircleElement,
  ClipPathElement,
  DefsElement,
  DescElement,
  Document,
  Element,
  EllipseElement,
  FeColorMatrixElement,
  FeCompositeElement,
  FeDropShadowElement,
  FeGaussianBlurElement,
  FeMorphologyElement,
  FilterElement,
  Font,
  FontElement,
  FontFaceElement,
  GElement,
  GlyphElement,
  GradientElement,
  ImageElement,
  LineElement,
  LinearGradientElement,
  MarkerElement,
  MaskElement,
  Matrix,
  MissingGlyphElement,
  Mouse,
  PSEUDO_ZERO,
  Parser,
  PathElement,
  PathParser,
  PatternElement,
  Point,
  PolygonElement,
  PolylineElement,
  Property,
  QB1,
  QB2,
  QB3,
  RadialGradientElement,
  RectElement,
  RenderedElement,
  Rotate,
  SVGElement,
  SVGFontLoader,
  Scale,
  Screen,
  Skew,
  SkewX,
  SkewY,
  StopElement,
  StyleElement,
  SymbolElement,
  TRefElement,
  TSpanElement,
  TextElement,
  TextPathElement,
  TitleElement,
  Transform,
  Translate,
  UnknownElement,
  UseElement,
  ViewPort,
  __tla,
  compressSpaces,
  Canvg as default, # here
  getSelectorSpecificity,
  normalizeAttributeName,
  normalizeColor,
  parseExternalUrl,
  index as presets,
  toNumbers,
  trimLeft,
  trimRight,
  vectorMagnitude,
  vectorsAngle,
  vectorsRatio
};
```

So I generated two `let` entries for them.

Now I fixed it and you all may test it later in the next version. Thanks for you all and especially @ztjhz for the reproduce!

**Comment by Menci** [comment]
Please try latest `v1.3.1`.

**Comment by ztjhz** [comment]
Thanks for the fixed!
